language: python            # this works for Linux but is an error on Windows
jobs:
  include:
    - name: "Python 3.6.7 on Ubuntu Bionic 18.04"
      python: 3.6           # this works for Linux but is ignored on Windows
      dist: bionic
      before_install:
        - sudo apt update
        - sudo apt install tesseract-ocr libtesseract-dev libleptonica-dev
    - name: "Python 3.7.1 on Ubuntu Bionic 18.04"
      python: 3.7           # this works for Linux but is ignored on Windows
      dist: bionic
      before_install:
        - sudo apt update
        - sudo apt install tesseract-ocr libtesseract-dev libleptonica-dev
    - name: "Python 3.8.0 on Ubuntu Bionic 18.04"
      python: 3.8           # this works for Linux but is ignored on Windows
      dist: bionic
      before_install:
        - sudo apt update
    - name: "Python 3.6.8 on Windows Server 1809"
      os: windows
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.6.8
        - python -m pip install --upgrade pip
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
    - name: "Python 3.7.6 on Windows Server 1809"
      os: windows
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.7.6
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
    - name: "Python 3.8 on Windows Server 1809"
      os: windows
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.8.6
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH

install:
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt
  - pip3 install flake8

script:
  - python3 -m flake8 || python -m flake8
  - find . | grep -E "\.py$" | xargs python -m compileall || dir /B *.py | python -m compileall

cache:
  - pip

notifications:
  email:
    - false
