language: python            # this works for Linux but is an error on Windows
jobs:
  include:
    - name: "Python 3.6.7 on Ubuntu Xenial 16.04"
      python: 3.6           # this works for Linux but is ignored on Windows
      dist: xenial
      before-install:
        - wget https://github.com/DanBloomberg/leptonica/releases/download/1.79.0/leptonica-1.79.0.tar.gz
        - tar xzf leptonica-1.79.0.tar.gz
        - cd leptonica-1.79.0
        - ./configure
        - make
        - sudo make install
        - cd ..
        - sudo apt-get install libtiff5 libtiffxx5 zlib1g
        - wget https://github.com/tesseract-ocr/tesseract/archive/4.1.1.tar.gz
        - tar xzf 4.1.1.tar.gz
        - cd tesseract-4.1.1
        - bash ./autogen.sh
        - ./configure
        - make 
        - sudo make install
    - name: "Python 3.7.1 on Ubuntu Xenial 16.04"
      python: 3.7           # this works for Linux but is ignored on Windows
      dist: xenial
      before-install:
        - sudo apt install tesseract-ocr libtesseract-dev libleptonica-dev pkg-config
    - name: "Python 3.8.0 on Ubuntu Xenial 16.04"
      python: 3.8           # this works for Linux but is ignored on Windows
      dist: xenial
      before-install:
        - sudo apt install tesseract-ocr libtesseract-dev libleptonica-dev pkg-config
    - name: "Python 3.6.8 on Windows Server 1809"
      os: windows
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.6.8
        - python -m pip install --upgrade pip
        - python -m pip install https://github.com/simonflueckiger/tesserocr-windows_build/releases/download/tesserocr-v2.4.0-tesseract-4.0.0/tesserocr-2.4.0-cp36-cp36m-win_amd64.whl
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
    - name: "Python 3.7.6 on Windows Server 1809"
      os: windows
      language: shell       # 'language: python' is an error on Travis CI Windows
      before_install:
        - choco install python --version 3.7.6
        - python -m pip install --upgrade pip
        - python -m pip install https://github.com/simonflueckiger/tesserocr-windows_build/releases/download/tesserocr-v2.4.0-tesseract-4.0.0/tesserocr-2.4.0-cp37-cp37m-win_amd64.whl
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH


install:
  - pip3 install --upgrade pip
  - pip3 install -r requirements.txt
  - pip3 install flake8

script:
  - python3 -m flake8 || python -m flake8
  - find . | grep -E "\.py$" | xargs python -m compileall || dir /B *.py | python -m compileall

cache:
  - pip

notifications:
  email:
    - false
